-- INSERT INTO TABLE_LOCATIONS(ID, NAME, PARENT_ID) VALUES (1, 'Inside', null);
-- INSERT INTO TABLE_LOCATIONS(ID, NAME, PARENT_ID) VALUES (2, 'Outside', null);
-- INSERT INTO TABLE_LOCATIONS(ID, NAME, PARENT_ID) VALUES (3, 'By the window', 1);
-- INSERT INTO TABLE_LOCATIONS(ID, NAME, PARENT_ID) VALUES (4, 'Inside the room', 1);
-- INSERT INTO TABLE_LOCATIONS(ID, NAME, PARENT_ID) VALUES (5, 'On the street', 2);
-- INSERT INTO TABLE_LOCATIONS(ID, NAME, PARENT_ID) VALUES (6, 'Inside the yard', 2);
--
-- INSERT INTO TABLES (ID, CAPACITY, LOCATION_ID) VALUES (1, 2, 3);
-- INSERT INTO TABLES (ID, CAPACITY, LOCATION_ID) VALUES (2, 6, 4);
-- INSERT INTO TABLES (ID, CAPACITY, LOCATION_ID) VALUES (3, 4, 5);
-- INSERT INTO TABLES (ID, CAPACITY, LOCATION_ID) VALUES (4, 10, 6);
--
-- INSERT INTO FOOD_CATEGORIES (ID, NAME, SERVING_TIME_FROM, SERVING_TIME_UNTIL) VALUES (1, 'Breakfast', '06:00', '10:00');
-- INSERT INTO FOOD_CATEGORIES (ID, NAME, SERVING_TIME_FROM, SERVING_TIME_UNTIL) VALUES (2, 'Daily lunch menu', '12:00', '15:00');
-- INSERT INTO FOOD_CATEGORIES (ID, NAME, SERVING_TIME_FROM, SERVING_TIME_UNTIL) VALUES (3, 'Cold meals', '06:00', '22:00');
-- INSERT INTO FOOD_CATEGORIES (ID, NAME, SERVING_TIME_FROM, SERVING_TIME_UNTIL) VALUES (4, 'Hot meals', '17:00', '22:00');
--
-- INSERT INTO APPLICATION_SETTINGS(ID, NAME, VALUE) VALUES (1, 'RESERVATION_DAYS', '2');

MERGE INTO USERS KEY (ID) VALUES (1, TRUE, 'user1', '$2a$10$Ongq1Twv1MbMczJFI5.lhepXlTz9pxMRxb48AMJhNJm/7hBB2RQVS');
